name: Auto Merge AI Branches

on:
  push:
    branches-ignore:
      - main  # only trigger for non-main branches

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          title: "Auto PR from ${{ env.BRANCH_NAME }}"
          body: "Automatically created by AI pipeline."

      - name: Auto Merge Pull Request
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
          MERGE_COMMIT_MESSAGE: "Auto merged PR from ${{ env.BRANCH_NAME }}"
