name: Auto Pull Request & Merge

on:
  push:
    branches:
      - "ai_generated/*"  # run whenever a branch with this prefix is pushed

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up GitHub CLI (for creating PRs)
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "${GITHUB_TOKEN}"

      # Create PR (or update if exists)
      - name: Create or update PR
        id: create_pr
        run: |
          gh pr create \
            --base main \
            --head $GITHUB_REF_NAME \
            --title "AI Generated Update: $GITHUB_REF_NAME" \
            --body "Automatically generated by AI pipeline" \
            --assignee @me || echo "PR might already exist"

      # Merge PR automatically
      - name: Merge PR
        if: success() || always()
        run: |
          PR_NUMBER=$(gh pr list --head $GITHUB_REF_NAME --json number -q '.[0].number')
          if [ "$PR_NUMBER" != "null" ]; then
            gh pr merge $PR_NUMBER --merge --admin
          else
            echo "No PR found to merge"
          fi
